/* Icon names editors can pick in /cms. Mapped to lucide icons in components/ui/Icon.tsx. */
export const iconOptions = [
  { title: "House", value: "house" },
  { title: "Commercial building", value: "building" },
  { title: "Wrench (repairs)", value: "wrench" },
  { title: "Hammer", value: "hammer" },
  { title: "Shield", value: "shield" },
  { title: "Shield check (warranty)", value: "shield-check" },
  { title: "Storm", value: "storm" },
  { title: "Siren (emergency)", value: "siren" },
  { title: "Water drop (leaks)", value: "droplets" },
  { title: "Clipboard (inspection)", value: "clipboard" },
  { title: "File check (claims)", value: "file-check" },
  { title: "Layers (materials)", value: "layers" },
  { title: "Award", value: "award" },
  { title: "Badge check", value: "badge-check" },
  { title: "Gutter / rain", value: "rain" },
  { title: "Wind", value: "wind" },
  { title: "Sun", value: "sun" },
  { title: "Ruler (measure)", value: "ruler" },
  { title: "Hard hat", value: "hard-hat" },
  { title: "Users (family)", value: "users" },
  { title: "Clock", value: "clock" },
  { title: "Phone", value: "phone" },
  { title: "Dollar (financing)", value: "dollar" },
  { title: "Star", value: "star" },
  { title: "Map pin", value: "map-pin" },
  { title: "Camera (photos)", value: "camera" },
  { title: "Handshake", value: "handshake" },
  { title: "Leaf", value: "leaf" },
  { title: "Thermometer", value: "thermometer" },
  { title: "Factory / warehouse", value: "warehouse" },
  { title: "Cross (faith)", value: "cross" },
  { title: "Bible", value: "book" },
  { title: "Hand and heart", value: "hand-heart" },
] as const;

export type IconName = (typeof iconOptions)[number]["value"];
